### ISSUE TITLE
Setup Backend Scaffold for Prisma/GraphQL

### ISSUE THREAD

**Issue by mvlhotra** [kaushjonna/recipEZ#10]
- [ ] Include all necessary dependencies #11
- [ ] Setup DB model, integrate properly with GraphQL #12
- [ ] Write basic resolvers #13
- [ ] Write basic mutations  #14
- [ ] Write basic subscriptions #15
